export const paddingSize = {
  xs: 'px-3c py-1c',
  s: 'px-4c py-2c',
  m: 'px-6c py-3c',
  l: 'px-8c py-5c ',
  xl: 'px-10c py-6c',
};

export const bgColor = {
  primary: 'bg-primary3 hover:bg-primary2',
  primaryPressed: 'bg-primary1 hover:bg-primary2',
  primaryGhost: 'border-primary3 hover:border-primary2',
  lightPrimary: 'bg-primary9 hover:bg-primary8',
  lightPrimaryPressed: 'bg-primary7 hover:bg-primary8',
  lightPrimaryGhost: 'border-primary7 hover:border-primary5 bg-primary10 hover:bg-primary9',
  gray: 'bg-gray11 hover:bg-gray10',
  grayPressed: 'bg-gray9 hover:bg-gray10',
  grayGhost: 'border-gray9 hover:border-gray5',
  plane: 'bg-gray13 hover:bg-gray11',
  planePressed: 'bg-gray9 hover:bg-gray11',
  planeGhost: 'border-gray9 hover:border-gray11',
  red: 'bg-red4 hover:bg-red2',
  redPressed: 'bg-red1 hover:bg-red2',
  redGhost: 'border-red3 hover:border-red2',
  lightRed: 'bg-red8 hover:bg-red7',
  lightRedPressed: 'bg-red6 hover:bg-red7',
  lightRedGhost: 'border-red8 hover:border-red7',
  blue: 'bg-blue1 hover:bg-blue2',
  bluePressed: 'bg-blue3 hover:bg-blue2',
  blueGhost: 'border-blue3 hover:border-blue2',
  lightBlue: 'bg-blue8 hover:bg-blue7',
  lightBluePressed: 'bg-blue6 hover:bg-blue7',
  lightBlueGhost: 'border-blue8 hover:border-blue7',
  purple: 'bg-purple1 hover:bg-purple2',
  purplePressed: 'bg-purple3 hover:bg-purple2',
  purpleGhost: 'border-purple6 hover:border-purple5',
  yellow: 'bg-yellow1 hover:bg-yellow2',
  yellowPressed: 'bg-yellow3 hover:bg-yellow2',
  yellowGhost: 'border-yellow6 hover:border-yellow5',
  teal: 'bg-teal1 hover:bg-teal2',
  tealPressed: 'bg-teal3 hover:bg-teal2',
  tealGhost: 'border-teal6 hover:border-teal5',
  pink: 'bg-pink1 hover:bg-pink2',
  pinkPressed: 'bg-pink3 hover:bg-pink2',
  pinkGhost: 'border-pink6 hover:border-pink5',
};

export const bgTextColor = {
  primary: 'bg-primary3 hover:bg-primary2 text-gray13',
  primaryPressed: 'bg-primary1 hover:bg-primary2 text-gray13',
  primaryGhost: 'border-primary3 hover:border-primary2 text-primary3 hover:text-primary2',
  lightPrimary: 'bg-primary9 hover:bg-primary8 text-primary2',
  lightPrimaryPressed: 'bg-primary7 hover:bg-primary8 text-primary1 hover:text-primary2',
  lightPrimaryGhost:
    'border-primary7 hover:border-primary5 bg-primary10 hover:bg-primary9 text-primary3 hover:text-primary2',
  gray: 'bg-gray11 hover:bg-gray10 text-gray2',
  grayPressed: 'bg-gray9 hover:bg-gray10 text-gray2',
  grayGhost: 'border-gray9 hover:border-gray11 text-gray2',
  plane: 'bg-gray13 hover:bg-gray11 text-gray2',
  planePressed: 'bg-gray9 hover:bg-gray11 text-gray2',
  planeGhost: 'border-gray9 hover:border-gray11 text-gray13',
  red: 'bg-red4 hover:bg-red2 text-gray13',
  redPressed: 'bg-red1 hover:bg-red2 text-gray13',
  redGhost: 'border-red3 hover:border-red2 text-red3 hover:text-red2',
  lightRed: 'bg-red8 hover:bg-red7 text-red3 hover:text-red2',
  lightRedPressed: 'bg-red6 hover:bg-red7 text-red1 hover:text-red2',
  lightRedGhost: 'border-red8 hover:border-red7 text-red8 hover:text-red7',
  blue: 'bg-blue1 hover:bg-blue2 text-gray13',
  bluePressed: 'bg-blue3 hover:bg-blue2 text-gray13',
  blueGhost: 'border-blue3 hover:border-blue2 text-blue3 hover:text-red2',
  lightBlue: 'bg-blue8 hover:bg-blue7 text-blue3 hover:text-blue2',
  lightBluePressed: 'bg-blue6 hover:bg-blue7 text-blue1 hover:text-blue2',
  lightBlueGhost: 'border-blue8 hover:border-blue7 text-blue8 hover:text-blue7',
  purple: 'bg-purple1 hover:bg-purple2 text-gray13',
  purplePressed: 'bg-purple3 hover:bg-purple2 text-gray13',
  purpleGhost: 'border-purple6 hover:border-purple5 text-purple3 hover:text-purple2',
  yellow: 'bg-yellow1 hover:bg-yellow2 text-gray13',
  yellowPressed: 'bg-yellow3 hover:bg-yellow2 text-gray13',
  yellowGhost: 'border-yellow6 hover:border-yellow5 text-yellow3 hover:text-yellow2',
  teal: 'bg-teal1 hover:bg-teal2 text-gray13',
  tealPressed: 'bg-teal3 hover:bg-teal2 text-gray13',
  tealGhost: 'border-teal6 hover:border-teal5 text-teal3 hover:text-teal2',
  pink: 'bg-pink1 hover:bg-pink2 text-gray13',
  pinkPressed: 'bg-pink3 hover:bg-pink2 text-gray13',
  pinkGhost: 'border-pink6 hover:border-pink5 text-pink3 hover:text-pink2',
};
